version: "3"

services:
  dev:
    container_name: dev
    build:
      context: .
      args:
        - PROXY=${http_proxy}
    tty: true
    environment:
      - http_proxy
      - https_proxy
    command: /bin/sh -c "while sleep 1000; do :; done"
